version: '3'
services:
  redis-server:
    image: redis
    ports:
      - "6379:6379" 
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
  # node-app:
  #   build: .
  #   ports:
  #     - "3000:3000"